#### 1.Import numpy as np

In [1]:
import numpy as np

#### 2.Create 10 zeroes

In [4]:
v=np.zeros(10,dtype=int)
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
matrice=np.zeros((1,10),dtype=int)
matrice

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 3.Create a vector with values ranging from 10 to 100

In [9]:
vector=np.arange(10,100)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### 4.Reverse it

In [10]:
vector_reverse=np.flip(vector)
vector_reverse

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 5.Reshape it to a 3x30

In [11]:
vector_reshape=np.reshape(vector,(3,30))
vector_reshape

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

#### 6.Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems

In [12]:
x=np.array([1,2,9,0,0,1,4,0])
x

array([1, 2, 9, 0, 0, 1, 4, 0])

In [13]:
#find indices of non-zero elems
indices=np.nonzero(x)
indices

(array([0, 1, 2, 5, 6], dtype=int64),)

#### 7.Create a 3x3 identity matrix

In [14]:
I=np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
I1=np.eye(3)
I1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8.Create a random vector of size 50 with values uniformely distributed in (-1, 1). Find the average of these values

In [20]:
vect_unif=np.random.uniform(-1,1,50)

#media valorilor vectorului

vect_mean=np.mean(vect_unif)
print(vect_unif)
print('media=',vect_mean)

[-0.39866502  0.88682734  0.56363356 -0.90713043  0.82938687 -0.4195621
  0.80051858  0.75000783  0.78763304  0.6416146  -0.5267668   0.76647644
  0.79844997  0.67630364 -0.11802685  0.26483824 -0.30716889  0.46296626
  0.67693517  0.73797376 -0.99840277 -0.62445607 -0.96103722  0.59753742
  0.69939847 -0.67523489  0.87616405 -0.63517636 -0.84733859 -0.38751376
 -0.70984139 -0.8969825   0.48754424 -0.45589034 -0.0133264   0.10127745
 -0.5164659   0.19875825 -0.82213521 -0.1504855  -0.25161031  0.10033643
 -0.01816429 -0.1998543   0.88618795 -0.7330674   0.46362303  0.85529248
 -0.15433564  0.71271737]
media= 0.05787527039467453


#### 9.Create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest

In [21]:
M=np.diag([1,2,3,4],-1)
M

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 10.Create a 5x3 matrix and a 3x4 one. Multiply them

In [26]:
#creez eu matricele

A=np.array([[1,2,1],[2,3,2],[1,3,2],[4,1,2],[1,5,2]])
B=np.array([[1,2,1,3],[2,3,2,7],[1,3,2,2]])
matrix_prod=np.dot(A,B)
print(A)
print(B)
print(matrix_prod)


[[1 2 1]
 [2 3 2]
 [1 3 2]
 [4 1 2]
 [1 5 2]]
[[1 2 1 3]
 [2 3 2 7]
 [1 3 2 2]]
[[ 6 11  7 19]
 [10 19 12 31]
 [ 9 17 11 28]
 [ 8 17 10 23]
 [13 23 15 42]]


In [42]:
#random matrix
A_5_3=np.random.random((5,3))
B_3_4=np.random.random((3,4))
matrix_prod=np.dot(A_5_3,B_3_4)
print(A_5_3)
print(B_3_4)
print(matrix_prod)

[[0.07387535 0.93074206 0.8750701 ]
 [0.90999282 0.59571911 0.93169103]
 [0.8358486  0.11098639 0.11247453]
 [0.05079595 0.31105604 0.38356712]
 [0.68932194 0.03600422 0.02995027]]
[[0.201949   0.87402303 0.18038083 0.84684539]
 [0.8519084  0.45682967 0.21345112 0.48579288]
 [0.30024657 0.25181774 0.05539189 0.74570218]]
[[1.07056283 0.71011752 0.26046541 1.16725055]
 [0.9710073  1.30211318 0.34291029 1.75478336]
 [0.29711911 0.80957588 0.18069141 0.84562343]
 [0.39041416 0.28308547 0.09680438 0.48015197]
 [0.17887264 0.62647305 0.1336846  0.62357368]]


#### 11.Using the previous matrix, extract a new one with just the integer part of the values. Find at least 4 methods of doing this

In [43]:
#metoda 1

M1=np.trunc(matrix_prod)
M1

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# metoda 2

M2=matrix_prod.astype(int)
print(M2)

[[1 0 0 1]
 [0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [60]:
# metoda 3

print(matrix_prod.shape)

def func1(x,y):
    return matrix_prod[x,y].astype(int)

M3=np.fromfunction(func1,(5,4), dtype=int)
print(M3)

(5, 4)
[[1 0 0 1]
 [0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 12. Create a random vector of size 25. Sort it

In [70]:
x = np.random.random(25)
print(x)
x.sort()
print("Sorted array:")
print(x)

[0.91362348 0.05406617 0.79029484 0.37466229 0.05114801 0.3259167
 0.82452919 0.0992634  0.49662392 0.97147351 0.52342812 0.63608158
 0.75946523 0.15835703 0.42144972 0.33588667 0.11630501 0.10692247
 0.82257426 0.46756874 0.87399416 0.53270957 0.26342337 0.41006819
 0.1252854 ]
Sorted array:
[0.05114801 0.05406617 0.0992634  0.10692247 0.11630501 0.1252854
 0.15835703 0.26342337 0.3259167  0.33588667 0.37466229 0.41006819
 0.42144972 0.46756874 0.49662392 0.52342812 0.53270957 0.63608158
 0.75946523 0.79029484 0.82257426 0.82452919 0.87399416 0.91362348
 0.97147351]


#### 13. Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.

In [78]:
Matrix_2D=np.random.random((7,2))
print(Matrix_2D)

[[0.28881354 0.02834774]
 [0.78378849 0.03950506]
 [0.19352278 0.50295832]
 [0.78076963 0.97570697]
 [0.44148206 0.38538767]
 [0.92117547 0.28901864]
 [0.9005156  0.33206954]]


In [87]:
# metoda 1

x = Matrix_2D[:,0]
y = Matrix_2D[:,1]

r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)


[0.29020141 0.78478344 0.53890457 1.24964207 0.58602907 0.9654512
 0.95979087]
[0.097839   0.05036009 1.20348867 0.89592787 0.7176625  0.30402309
 0.3532843 ]


In [99]:
# metoda 2

def coordonate_polare (x,y):
    rho = np.sqrt(Matrix_2D[x,0]**2 + Matrix_2D[x,1]**2)
    phi = np.arctan2(Matrix_2D[x,1], Matrix_2D[x,0])
    return rho , phi

C_p=np.fromfunction(coordonate_polare,(7,1), dtype=int)
C_p

(array([[0.29020141],
        [0.78478344],
        [0.53890457],
        [1.24964207],
        [0.58602907],
        [0.9654512 ],
        [0.95979087]]), array([[0.097839  ],
        [0.05036009],
        [1.20348867],
        [0.89592787],
        [0.7176625 ],
        [0.30402309],
        [0.3532843 ]]))

#### 14. Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it

In [76]:
M=np.random.random((10,10))
y=np.random.random()
print(M)
print(y)

[[0.16090968 0.06269742 0.03882838 0.15387725 0.1701972  0.34175742
  0.45025956 0.31710176 0.89956537 0.54924852]
 [0.18258379 0.3308134  0.4000237  0.77453815 0.56329651 0.82052819
  0.87240891 0.63512372 0.20913545 0.22402067]
 [0.95445201 0.7379712  0.43501504 0.41084762 0.13869263 0.22268838
  0.6826779  0.04444337 0.23963502 0.68829892]
 [0.54521276 0.47951532 0.70724704 0.53962453 0.50523781 0.09377656
  0.71967427 0.5017703  0.26475291 0.30417385]
 [0.21873018 0.88444491 0.22874146 0.58121525 0.32901072 0.95605256
  0.1491395  0.14955068 0.40916258 0.71625039]
 [0.73621225 0.25956496 0.42413605 0.27131129 0.18587879 0.59313349
  0.14933748 0.88518377 0.38413719 0.45060094]
 [0.62261331 0.01869865 0.05569608 0.97109346 0.98690969 0.61393143
  0.36479535 0.62276479 0.09814572 0.64717131]
 [0.96472757 0.22311081 0.76712853 0.60029322 0.22623543 0.46403324
  0.15058226 0.74918923 0.62244141 0.85883111]
 [0.81149487 0.37119998 0.14626298 0.71731958 0.11746261 0.3389055
  0.16659742 

In [77]:
nr_gasit=M.flat[np.abs(M-y).argmin()]
print(nr_gasit)

0.9544520127387164
